package com.woniuxy.pojo;

public class Clazz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.cid
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.cname
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    private String cname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.cid
     *
     * @return the value of clazz.cid
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.cid
     *
     * @param cid the value for clazz.cid
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.cname
     *
     * @return the value of clazz.cname
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.cname
     *
     * @param cname the value for clazz.cname
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    public void setCname(String cname) {
        this.cname = cname;
    }
}