package com.woniuxy.pojo;

public class Jianda {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianda.jianda_id
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    private Integer jiandaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianda.title
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianda.answer
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianda.typeid
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianda.test_question_id
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    private Integer testQuestionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianda.jianda_id
     *
     * @return the value of jianda.jianda_id
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public Integer getJiandaId() {
        return jiandaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianda.jianda_id
     *
     * @param jiandaId the value for jianda.jianda_id
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public void setJiandaId(Integer jiandaId) {
        this.jiandaId = jiandaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianda.title
     *
     * @return the value of jianda.title
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianda.title
     *
     * @param title the value for jianda.title
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianda.answer
     *
     * @return the value of jianda.answer
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianda.answer
     *
     * @param answer the value for jianda.answer
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianda.typeid
     *
     * @return the value of jianda.typeid
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianda.typeid
     *
     * @param typeid the value for jianda.typeid
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianda.test_question_id
     *
     * @return the value of jianda.test_question_id
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public Integer getTestQuestionId() {
        return testQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianda.test_question_id
     *
     * @param testQuestionId the value for jianda.test_question_id
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public void setTestQuestionId(Integer testQuestionId) {
        this.testQuestionId = testQuestionId;
    }
}