package com.woniuxy.pojo;

public class TestQuestions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_questions.test_question_id
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    private Integer testQuestionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_questions.Columntest_question_name_2
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    private String columntestQuestionName2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_questions.test_question_id
     *
     * @return the value of test_questions.test_question_id
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public Integer getTestQuestionId() {
        return testQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_questions.test_question_id
     *
     * @param testQuestionId the value for test_questions.test_question_id
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public void setTestQuestionId(Integer testQuestionId) {
        this.testQuestionId = testQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_questions.Columntest_question_name_2
     *
     * @return the value of test_questions.Columntest_question_name_2
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public String getColumntestQuestionName2() {
        return columntestQuestionName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_questions.Columntest_question_name_2
     *
     * @param columntestQuestionName2 the value for test_questions.Columntest_question_name_2
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public void setColumntestQuestionName2(String columntestQuestionName2) {
        this.columntestQuestionName2 = columntestQuestionName2;
    }
}