package com.woniuxy.pojo;

public class TestQuestions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_questions.test_question_id
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    private Integer testQuestionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_questions.test_question_name
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    private String testQuestionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_questions.typeid
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    private Integer typeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_questions.test_question_id
     *
     * @return the value of test_questions.test_question_id
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    public Integer getTestQuestionId() {
        return testQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_questions.test_question_id
     *
     * @param testQuestionId the value for test_questions.test_question_id
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    public void setTestQuestionId(Integer testQuestionId) {
        this.testQuestionId = testQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_questions.test_question_name
     *
     * @return the value of test_questions.test_question_name
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    public String getTestQuestionName() {
        return testQuestionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_questions.test_question_name
     *
     * @param testQuestionName the value for test_questions.test_question_name
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    public void setTestQuestionName(String testQuestionName) {
        this.testQuestionName = testQuestionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_questions.typeid
     *
     * @return the value of test_questions.typeid
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_questions.typeid
     *
     * @param typeid the value for test_questions.typeid
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }
}