package com.woniuxy.pojo;

public class Tiankong {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiankong.tiankong_id
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    private Integer tiankongId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiankong.title
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiankong.answer
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiankong.typeid
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiankong.test_question_id
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    private Integer testQuestionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiankong.tiankong_id
     *
     * @return the value of tiankong.tiankong_id
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    public Integer getTiankongId() {
        return tiankongId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiankong.tiankong_id
     *
     * @param tiankongId the value for tiankong.tiankong_id
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    public void setTiankongId(Integer tiankongId) {
        this.tiankongId = tiankongId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiankong.title
     *
     * @return the value of tiankong.title
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiankong.title
     *
     * @param title the value for tiankong.title
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiankong.answer
     *
     * @return the value of tiankong.answer
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiankong.answer
     *
     * @param answer the value for tiankong.answer
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiankong.typeid
     *
     * @return the value of tiankong.typeid
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiankong.typeid
     *
     * @param typeid the value for tiankong.typeid
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiankong.test_question_id
     *
     * @return the value of tiankong.test_question_id
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    public Integer getTestQuestionId() {
        return testQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiankong.test_question_id
     *
     * @param testQuestionId the value for tiankong.test_question_id
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    public void setTestQuestionId(Integer testQuestionId) {
        this.testQuestionId = testQuestionId;
    }
}