package com.woniuxy.pojo;

public class Tree {
	private boolean open = true;
    public boolean isOpen() {
		return open;
	}

	public void setOpen(boolean open) {
		this.open = open;
	}
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.tid
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.tname
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.url
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.pid
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.icon
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.tid
     *
     * @return the value of tree.tid
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.tid
     *
     * @param tid the value for tree.tid
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.tname
     *
     * @return the value of tree.tname
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.tname
     *
     * @param tname the value for tree.tname
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    public void setTname(String tname) {
        this.tname = tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.url
     *
     * @return the value of tree.url
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.url
     *
     * @param url the value for tree.url
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.pid
     *
     * @return the value of tree.pid
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.pid
     *
     * @param pid the value for tree.pid
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.icon
     *
     * @return the value of tree.icon
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.icon
     *
     * @param icon the value for tree.icon
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }
}