package com.woniuxy.pojo;

public class Trueorfalse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TrueorFalse.tf_id
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    private Integer tfId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TrueorFalse.title
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TrueorFalse.answer
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TrueorFalse.typeid
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TrueorFalse.test_question_id
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    private Integer testQuestionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TrueorFalse.tf_id
     *
     * @return the value of TrueorFalse.tf_id
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public Integer getTfId() {
        return tfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TrueorFalse.tf_id
     *
     * @param tfId the value for TrueorFalse.tf_id
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public void setTfId(Integer tfId) {
        this.tfId = tfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TrueorFalse.title
     *
     * @return the value of TrueorFalse.title
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TrueorFalse.title
     *
     * @param title the value for TrueorFalse.title
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TrueorFalse.answer
     *
     * @return the value of TrueorFalse.answer
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TrueorFalse.answer
     *
     * @param answer the value for TrueorFalse.answer
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TrueorFalse.typeid
     *
     * @return the value of TrueorFalse.typeid
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TrueorFalse.typeid
     *
     * @param typeid the value for TrueorFalse.typeid
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TrueorFalse.test_question_id
     *
     * @return the value of TrueorFalse.test_question_id
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public Integer getTestQuestionId() {
        return testQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TrueorFalse.test_question_id
     *
     * @param testQuestionId the value for TrueorFalse.test_question_id
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    public void setTestQuestionId(Integer testQuestionId) {
        this.testQuestionId = testQuestionId;
    }
}