package com.woniuxy.mapper;

import com.woniuxy.pojo.Jianda;
import com.woniuxy.pojo.JiandaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JiandaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    long countByExample(JiandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    int deleteByExample(JiandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    int deleteByPrimaryKey(String jiandaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    int insert(Jianda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    int insertSelective(Jianda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    List<Jianda> selectByExample(JiandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    Jianda selectByPrimaryKey(String jiandaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") Jianda record, @Param("example") JiandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    int updateByExample(@Param("record") Jianda record, @Param("example") JiandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    int updateByPrimaryKeySelective(Jianda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Fri Aug 23 14:56:06 CST 2019
     */
    int updateByPrimaryKey(Jianda record);
}