package com.woniuxy.mapper;

import com.woniuxy.pojo.Jianda;
import com.woniuxy.pojo.JiandaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JiandaMapper {
    List<Jianda> findByPage(Integer page,Integer limit);

    List<Jianda> findAll();

    Jianda findByName(String name);

    List<Jianda> findByQType(String typeQname);

    List<Jianda> findByType(String typeName);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    long countByExample(JiandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int deleteByExample(JiandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int deleteByPrimaryKey(Integer jiandaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int insert(Jianda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int insertSelective(Jianda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    List<Jianda> selectByExample(JiandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    Jianda selectByPrimaryKey(Integer jiandaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") Jianda record, @Param("example") JiandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int updateByExample(@Param("record") Jianda record, @Param("example") JiandaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int updateByPrimaryKeySelective(Jianda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianda
     *
     * @mbg.generated Sat Aug 24 13:08:25 CST 2019
     */
    int updateByPrimaryKey(Jianda record);
}