package com.woniuxy.mapper;

import com.woniuxy.pojo.Tree;
import com.woniuxy.pojo.TreeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tree
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    long countByExample(TreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tree
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    int deleteByExample(TreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tree
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    int deleteByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tree
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    int insert(Tree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tree
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    int insertSelective(Tree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tree
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    List<Tree> selectByExample(TreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tree
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    Tree selectByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tree
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") Tree record, @Param("example") TreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tree
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    int updateByExample(@Param("record") Tree record, @Param("example") TreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tree
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    int updateByPrimaryKeySelective(Tree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tree
     *
     * @mbg.generated Tue Aug 27 15:34:19 CST 2019
     */
    int updateByPrimaryKey(Tree record);
}