package com.woniuxy.mapper;

import com.woniuxy.pojo.Trueorfalse;
import com.woniuxy.pojo.TrueorfalseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrueorfalseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    long countByExample(TrueorfalseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    int deleteByExample(TrueorfalseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    int deleteByPrimaryKey(Integer tfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    int insert(Trueorfalse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    int insertSelective(Trueorfalse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    List<Trueorfalse> selectByExample(TrueorfalseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    Trueorfalse selectByPrimaryKey(Integer tfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") Trueorfalse record, @Param("example") TrueorfalseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    int updateByExample(@Param("record") Trueorfalse record, @Param("example") TrueorfalseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    int updateByPrimaryKeySelective(Trueorfalse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TrueorFalse
     *
     * @mbg.generated Sat Aug 24 12:21:22 CST 2019
     */
    int updateByPrimaryKey(Trueorfalse record);
}